run:
  timeout: 10m

linters-settings:
  dupl:
    threshold: 150 # minimal duplicate size

  exhaustive:
    default-signifies-exhaustive: false

  funlen:
    lines: 100 # maximum count of code lines
    statements: 50 # maximum count of code lines

  goconst:
    min-len: 2 # length of repeating string
    min-occurrences: 2 # number of occurences of string

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 25 # cyclical complexity

  goimports:
    local-prefixes: "txservice"

  golint:
    min-confidence: 0 # minimum confidence score for detected issues

  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return # don't include the "operation" and "assign"

  govet:
    check-shadowing: true

  lll:
    line-length: 160

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

  wsl:
    allow-trailing-comment: true
    allow-cuddle-declarations: false

  nestif:
    min-complexity: 3

service:
  golangci-lint-version: 1.32.2

skip-dirs:
  - e2e

linters:
  disable-all: true
  enable:
    - tparallel
    - nestif
    - govet # Suspicious constructs
    - errcheck # Unchecked errors
    - staticcheck # Static analysis checks
    - unused # Unused constants, variables, functions
    - gosimple # Simplify a code
    - structcheck # Unused struct fields
    - varcheck # Unused global variables and constants
    - ineffassign # Unused assignments to existing variables
    - deadcode # Unused code
    - typecheck # Parses and type-checks Go code
    - rowserrcheck # database/sql.Rows.Err() checked
    - stylecheck # golint analogue
    - unconvert # Unnecessary type conversions
    - goconst # Repeated strings that could be replaced by a constant
    - gofmt # Whether the code was gofmt-ed
    - goimports # Unused imports
    - golint # Style mistakes
    - misspell # Misspelled English words in comments
    - unparam # Unused function parameters
    - nakedret # Naked returns in functions greater than a specified function length (?)
    - scopelint # Unpinned variables in go programs
    - whitespace # Detection of leading and trailing whitespace
    - goprintffuncname # Printf-like functions are named with f at the end
    - nolintlint # Ill-formed or insufficient nolint directives
    - depguard # Package imports are in a list of acceptable packages
    - wsl
    - dupl
    - bodyclose
    - goerr113
    - gomnd
    - interfacer
    - prealloc
    - exportloopref

  # - gochecknoinits # No init functions are present in Go code
  # - lll # Long lines
  # - bodyclose # HTTP response body is closed successfully
  # - gosec # Security problems
  # - prealloc # Slice declarations that could potentially be preallocated
  # - goerr113 # Check the errors handling expressions
  # - dupl # Code clone detection
  # - wsl # Forces you to use empty lines!
  # - funlen # Long functions
  # - dogsled # Assignments with too many blank identifiers (e.g. x, , , _, := f())
  # - asciicheck # Non-ASCII identifiers
  # - exportloopref # Exporting pointers for loop variables
  # - exhaustive # Exhaustiveness of enum switch statements
  # - gochecknoglobals # No globals are present in Go code
  # - gocognit # Cognitive complexity of functions
  # - godot # Comments end in a period
  # - godox # Detection of FIX ME, TO DO and other comment keywords
  # - nestif # Deeply nested if statements
  # - gomodguard # Block list linter for direct Go module dependencies
  # - testpackage # Use a separate _test package
  # - maligned # Structs that would take less memory if their fields were sorted
